<?php

define('BKT_MODULAR_THEME_VERSION', '0.1.202203052030');
define('BKT_MODULAR_THEME_STYLES_VERSION', BKT_MODULAR_THEME_VERSION);
define('BKT_MODULAR_THEME_SCRIPTS_VERSION', BKT_MODULAR_THEME_VERSION);
define('BKT_MODULAR_THEME_SLUG', 'bkt');
